### ISSUE TITLE
Date fields may display as date-time stamps

### ISSUE THREAD

**Issue by nassibnassar** [library-data-platform/ui-ldp#20]
There has been a report that date fields show up as date-time stamps, i.e. including zeros for the time.  If true, it may be that this app is not distinguishing between date types and date-time stamp types.  However, it could be that the dates in question are encoded by FOLIO as time-stamps or interpreted by LDP as time-stamps, in which case there is no bug in this app and there may be a bug elsewhere.

**Comment by MikeTaylor** [comment]
Some investigation later, I can verify that timestamps appear with a time part:
> 2017-02-17T08:43:15.000+00:00

But it turns out that the only date- or time-related columns type I am seeing is `timestamp with time zone` — in fact, the only types I am seeing at all are this, `boolean` and `character varying`, so our universe of types is not very expansive.

I assume this reflects the set of types in use in the actual LDP database? I'm not familiar with Postgres types, but evidently `timestamp with time zone` does indeed include a time part — and indeed it would be odd to have a timezone without a time.

So my conclusion, I think, is that mod-ldp is simply reporting exactly what it gets back from the LDP database; and the UI is certainly just reporting what it gets from mod-ldp.

If that's correct, then the only honest thing for both mod-ldp and ui-ldp to do right now is what they're doing now. (There is a dishonest option, which is to special-case the timestamp `T00:00:00.000` but that would make me very uncomfortable.)

Further down the line we may want to expand the set of types used by the LDP Postgres database to better reflect the richness of the type system in FOLIO itself. When that has been done, corresponding changes _may_ be required in mod-ldp, ui-ldp or both; or maybe it will Just Work, since at present neither of them is at all concerned with types.

**Comment by MikeTaylor** [comment]
@nassibnassar If you agree, I will close this as INVALID.

**Comment by nassibnassar** [comment]
I have sent a note requesting specific fields where this possible problem was seen.

**Comment by MikeTaylor** [comment]
By all means — that would be good to know — but I am 99.6% certain they will prove to be `timestamp with time zone` fields.

**Comment by MikeTaylor** [comment]
@nassibnassar What types of fields does LDP create in its Postgres database, in fact?

**Comment by nassibnassar** [comment]
Correct.  The problem is in ldp.  Closing this issue.

Pre-Metadb the types are:
* bigint
* boolean
* numeric(12,2)
* timestamptz
* varchar
(subject to additions)

Metadb expands this list to some extent.  User-defined tables can include any types, but supporting all types here is relatively low priority.
