### ISSUE TITLE
http status 500: internal server error

### ISSUE THREAD

**Issue by nassibnassar** [library-data-platform/ui-ldp#51]
http status 500 (internal server error) seems to be reproducible with this sequence of steps:

1. select table `public.course_courses`, order by column `id`, and submit
2. select table `folio_reporting.instance_notes` and submit

**Comment by MikeTaylor** [comment]
Confirmed.

**Comment by MikeTaylor** [comment]
The 500 response from mod-ldp doesn't say anything more than "500 internal server error", but I am pretty confident that this is because `folio_reporting.instance_notes` doesn't have an `id` field and the query being sent asks for one:
```
{
  "tables": [
    {
      "schema": "folio_reporting",
      "tableName": "instance_notes",
      "columnFilters": [
        {}
      ],
      "showColumns": [],
      "orderBy": [
        {
          "direction": "asc",
          "nulls": "end",
          "key": "id"
        }
      ],
      "limit": 101
    }
  ]
}
```

So there are two issues here. One is that mod-ldp is bad at reporting errors: there should be some kind of `try`/`catch` block around the logic that reports something useful in the body of the 500 response.

But more immediately, when you change the selected schema, the ordering criteria should be cleared so that the UI never sends this bad request.
